### ISSUE TITLE
MySQL password is exposed

### ISSUE THREAD

**Issue by h33raj** [powerdevacademy/bethehero#1]
![image](https://user-images.githubusercontent.com/9161506/83322169-04eb4180-a288-11ea-9e59-6ff24a8b5641.png)

https://github.com/powerdevacademy/bethehero/blob/f44ff328d8bc0d88ccb69cf113dbba29fd06282e/backend/knexfile.js --> You can change the password to secure the system, remove the password from further commits

**Comment by danielojingo** [comment]
Thanks @h33raj, will do it

**Comment by powerdevacademy** [comment]
Thanks!
